### ISSUE TITLE
Preparar jogo

### ISSUE THREAD

**Issue by Vi-Jays** [joaroque/gigabot-plus#1]
Traceback (most recent call last):
  File "gb.py", line 380, in <module>
    main()
  File "gb.py", line 324, in main
    gb.session_init()
AttributeError: 'Gigabot' object has no attribute 'session_init'

**Comment by joaroque** [comment]
Olá @ViktorJays, tudo bom?

Na parte de "Preparar o jogo foi descontinuado, pois ele se aproveitava dos bugs de vários jogos por dia em navegadores diferentes. Quando o portal foi cancelado esse bug parou de funcionar pois dependia dos navegadores.~

Vou já editar o código. Muito obrigado e não esqueça de dar uma estrela no projecto 👍🏽
