### ISSUE TITLE
Vendas de jogos

### ISSUE THREAD

**Issue by Vi-Jays** [joaroque/gigabot-plus#2]
@joaroque só pelo pouco que analisei o seu programa, ele tem se mostrado muito eficaz e agradeço bastante que tenha partilhado com a comunidade.
Eu sou Angolano e percebo de tecnologias e tal mas esse seu projecto é extraordinário.
Quero fazer um pedido meio egoísta mas espero que entenda: é possível apagar esse projecto do gigabot?
Tem pessoas que já estão a fazer mal uso do seu projecto e até estão a engariar fundos com o mesmo, apesar de ser OpenSource, os créditos e a propriedade intelectual pertencem a si.
Bem, a decisão é apenas sua e quero já aproveitar esta oportunidade em dizer que me tornei um fã kkkkkk
Você me fez gostar de python, não por causa de ganhar gigas com isso, mas porque é possível desenvolver algo com o mesmo sem que tenha necessariamente envolvimento com IA.
.
cumps
.
att: perdoa-me por usar o issue para isso

**Comment by joaroque** [comment]
Olá de novo @ViktorJays 😊

Muito obrigado pelo elogio e admiração. Sobre o mal uso do script eu falo simplesmente que **não me importo**.
Eu já o desenvolvi e não queria retroceder, se as pessoas parassem de pensar só em si esse país seria muito melhor.

O portal está no fim então seria irrelevante apagar o projecto agora. Mas com tudo agradeço pelo feedback e olha que você não é única pessoa que me diz isso. Vamos tornar o país menos orgulho e mais humilde


Valeu 👍🏽
